name: Laravel

on: [push]

jobs:
  laravel:
    runs-on: ubuntu-latest

    step:
      - uses: actions/checkout@v1
      - name: Install composer dependencies
        run: composer install
      - name: Install node dependecies
        run: npm install
      - name: Compile and mix assets
        run: npm run dev
      - name: Run tests
        run: ./vendor/bin/phpunit
